version: '3'
services:
  front-end:
    build: ./frontend
    ports:
      - '5173:5173'
    environment:
      VITE_API_URL: http://localhost:8080
  back-end:
    build: ./backend
    ports:
      - '8080:8080'
    env_file:
      - ./backend/.env
    command: bash -c "python manage.py runserver 0.0.0.0:8080"
